
# configure default values for pull request tests
test:
  hostprovider: gke

  gardensetup:
    revision: "master"

  gardener:
    version: "0.30.0"

  gardener-extensions: 
    value: |
      dns-external:
          repo: "https://github.com/gardener/external-dns-management.git"
          version: "latest"
      networking-calico:
          repo: "https://github.com/gardener/gardener-extensions.git"
          version: "latest"
      os-coreos:
          repo: "https://github.com/gardener/gardener-extensions.git"
          version: "latest"
      os-suse-jeos:
          repo: "https://github.com/gardener/gardener-extensions.git"
          version: "latest"
      os-ubuntu:
          repo: "https://github.com/gardener/gardener-extensions.git"
          version: "latest"
      provider-aws:
          repo: "https://github.com/gardener/gardener-extensions.git"
          version: "latest"
      provider-azure:
          repo: "https://github.com/gardener/gardener-extensions.git"
          version: "latest"
      provider-gcp:
          repo: "https://github.com/gardener/gardener-extensions.git"
          version: "latest"
      provider-openstack:
          repo: "https://github.com/gardener/gardener-extensions.git"
          version: "latest"

  shootFlavors:
  - provider: gcp
    kubernetes:
      versions:
      - version: 1.15.5
  - provider: aws
    kubernetes:
      versions:
      - version: 1.15.5
